typography_spectrum: 0.5682957
color:
  saturation: 0.6426451988518238
  brandStrength: 0.875577031634748
  rhythmicContrast: 0.9135414138436317
  brandColors:
    - '#D1D1D1'
    - '#686868'
    - '#878787'
    - '#373737'
    - '#0C0C0C'
  lightness: 0.4706348415929824
layout_spectrum: 0.1704261
name: MarcosMedeiros
navigation:
  - name: about me
    id: ef825edd-f6a2-409f-bb9b-c71051742bac
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MY SQUARE EYES
description: ''
